module.exports = {
  "ALIVE_IMG": "https://i.imghippo.com/files/yFpQ9125wYo.jpg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "inbox",
  "BOT_NUMBER": "923143702270",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": false,
  "AUTO_REACT": true,
  "WELCOME": true,
  "ANTI_BAD": true,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ANTI_CALL": false,
  "ANTI_DELETE": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": false,
  "BTN_MSG": false,
  "OWNER_NAME": "♥️🌸⃝𝐂𝐮𝐭𝐞 𝐬𝐡𝐞𝐢𝐤𝐡ᥫ᭡👑",
  "NEWS_JID": "923143702270@s.whatsapp.net",
  "AUTO_TYPING": true,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": true,
  "EMOJI": "🏷"
};
